# Generated by Django 4.0.4 on 2023-07-21 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pricing_module.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('base_distance', models.DecimalField(decimal_places=1, max_digits=8)),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('distance_additional_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_multiplier_factor', models.CharField(max_length=200, validators=[pricing_module.models.validate_tmf_choices])),
                ('waiting_charges', models.DecimalField(decimal_places=2, max_digits=8)),
                ('waiting_time_threshold', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='pricingconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('day',), name='unique_day_for_active_true'),
        ),
    ]
