# Generated by Django 4.0.4 on 2023-07-20 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pricing_module.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('base_distance', models.DecimalField(decimal_places=1, max_digits=8)),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('distance_additional_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_multiplier_factor', models.CharField(max_length=200, validators=[pricing_module.models.validate_tmf_choices])),
                ('waiting_charges', models.DecimalField(decimal_places=2, max_digits=8)),
                ('waiting_time_threshold', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('day', 'is_active')},
            },
        ),
    ]
